# Generated by Django 5.2.8 on 2025-12-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistas', '0007_tour_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='precio',
            field=models.CharField(blank=True, default='7.5M', max_length=20, null=True),
        ),
    ]
